### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by SteveMcArthur** [26medias/social-login#2]
Hi

You're missing the following dependencies from the package.json files:
passport
passport-youtube-v3
passport-github

**Comment by SteveMcArthur** [comment]
I've had a second look at the package.json and these dependencies seem to be there. Possibly a version issue going on here

**Comment by cm45t3r** [comment]
Hi,

Same happened to me at the npm package (v2.1.1) that is out of date.

**Comment by 26medias** [comment]
This project is not maintained anymore.
Feel free to fork and take over.
