### ISSUE TITLE
Caching code breaking tests

### ISSUE THREAD

**Issue by SteveMcArthur** [26medias/social-login#6]
The caching code in the NPM version is causing my tests to hang. I don't really know why and I can't quite work out what the caching code is supposed to do.

**Comment by 26medias** [comment]
There has been changes to the facebook API and the API of other social networks, which might be why it's not working anymore.
That project has been on pause for a few months and will restart in July.

**Comment by SteveMcArthur** [comment]
Hi - I'm fine with the project being paused. I'm using a modified version of the code now. Can you give me a hint at what the caching code is supposed to do? It only causes problems with tests - not anything else.
